/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118382-g1911a6ec26-20250130"
#endif /* AVUTIL_FFVERSION_H */
